// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/orchestrator/orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNKNOWN JobState = 0
	JobState_QUEUED            JobState = 1
	JobState_RUNNING           JobState = 2
	JobState_COMPLETED         JobState = 3
	JobState_FAILED            JobState = 4
	JobState_CANCELLED         JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNKNOWN",
		1: "QUEUED",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNKNOWN": 0,
		"QUEUED":            1,
		"RUNNING":           2,
		"COMPLETED":         3,
		"FAILED":            4,
		"CANCELLED":         5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestrator_orchestrator_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_proto_orchestrator_orchestrator_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

type JobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Requirements   *DeviceRequirements    `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *JobRequest) GetRequirements() *DeviceRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type DeviceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinSdk        int32                  `protobuf:"varint,1,opt,name=min_sdk,json=minSdk,proto3" json:"min_sdk,omitempty"`
	MaxSdk        int32                  `protobuf:"varint,2,opt,name=max_sdk,json=maxSdk,proto3" json:"max_sdk,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequirements) Reset() {
	*x = DeviceRequirements{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequirements) ProtoMessage() {}

func (x *DeviceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequirements.ProtoReflect.Descriptor instead.
func (*DeviceRequirements) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceRequirements) GetMinSdk() int32 {
	if x != nil {
		return x.MinSdk
	}
	return 0
}

func (x *DeviceRequirements) GetMaxSdk() int32 {
	if x != nil {
		return x.MaxSdk
	}
	return 0
}

func (x *DeviceRequirements) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceRequirements) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

type JobOutput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State          JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=orchestrator.JobState" json:"state,omitempty"`
	Stdout         string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr         string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode       int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	QueuePosition  int32                  `protobuf:"varint,6,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	AssignedDevice *DeviceInfo            `protobuf:"bytes,7,opt,name=assigned_device,json=assignedDevice,proto3" json:"assigned_device,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobOutput) Reset() {
	*x = JobOutput{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOutput) ProtoMessage() {}

func (x *JobOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOutput.ProtoReflect.Descriptor instead.
func (*JobOutput) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *JobOutput) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobOutput) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNKNOWN
}

func (x *JobOutput) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *JobOutput) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *JobOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobOutput) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *JobOutput) GetAssignedDevice() *DeviceInfo {
	if x != nil {
		return x.AssignedDevice
	}
	return nil
}

func (x *JobOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State          JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=orchestrator.JobState" json:"state,omitempty"`
	ExitCode       int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AssignedDevice *DeviceInfo            `protobuf:"bytes,5,opt,name=assigned_device,json=assignedDevice,proto3" json:"assigned_device,omitempty"`
	QueuePosition  int32                  `protobuf:"varint,6,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNKNOWN
}

func (x *JobStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobStatus) GetAssignedDevice() *DeviceInfo {
	if x != nil {
		return x.AssignedDevice
	}
	return nil
}

func (x *JobStatus) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{5}
}

type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*DeviceSourceInfo    `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceList) GetSources() []*DeviceSourceInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

type DeviceSourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Devices       []*DeviceInfo          `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSourceInfo) Reset() {
	*x = DeviceSourceInfo{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSourceInfo) ProtoMessage() {}

func (x *DeviceSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSourceInfo.ProtoReflect.Descriptor instead.
func (*DeviceSourceInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceSourceInfo) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DeviceSourceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeviceSourceInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DeviceSourceInfo) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Sdk           int32                  `protobuf:"varint,4,opt,name=sdk,proto3" json:"sdk,omitempty"`
	Release       int32                  `protobuf:"varint,5,opt,name=release,proto3" json:"release,omitempty"`
	Busy          bool                   `protobuf:"varint,6,opt,name=busy,proto3" json:"busy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetSdk() int32 {
	if x != nil {
		return x.Sdk
	}
	return 0
}

func (x *DeviceInfo) GetRelease() int32 {
	if x != nil {
		return x.Release
	}
	return 0
}

func (x *DeviceInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	QueuedJobs       int32                  `protobuf:"varint,2,opt,name=queued_jobs,json=queuedJobs,proto3" json:"queued_jobs,omitempty"`
	RunningJobs      int32                  `protobuf:"varint,3,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	AvailableDevices int32                  `protobuf:"varint,4,opt,name=available_devices,json=availableDevices,proto3" json:"available_devices,omitempty"`
	ActiveSessions   int32                  `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetQueuedJobs() int32 {
	if x != nil {
		return x.QueuedJobs
	}
	return 0
}

func (x *PingResponse) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *PingResponse) GetAvailableDevices() int32 {
	if x != nil {
		return x.AvailableDevices
	}
	return 0
}

func (x *PingResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

type AcquireDeviceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Requirements       *DeviceRequirements    `protobuf:"bytes,1,opt,name=requirements,proto3" json:"requirements,omitempty"`
	TimeoutSeconds     int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IdleTimeoutSeconds int32                  `protobuf:"varint,3,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AcquireDeviceRequest) Reset() {
	*x = AcquireDeviceRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireDeviceRequest) ProtoMessage() {}

func (x *AcquireDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireDeviceRequest.ProtoReflect.Descriptor instead.
func (*AcquireDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *AcquireDeviceRequest) GetRequirements() *DeviceRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *AcquireDeviceRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AcquireDeviceRequest) GetIdleTimeoutSeconds() int32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

type AcquireDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Device        *DeviceInfo            `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireDeviceResponse) Reset() {
	*x = AcquireDeviceResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireDeviceResponse) ProtoMessage() {}

func (x *AcquireDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireDeviceResponse.ProtoReflect.Descriptor instead.
func (*AcquireDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *AcquireDeviceResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AcquireDeviceResponse) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

type SessionCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionCommand) Reset() {
	*x = SessionCommand{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCommand) ProtoMessage() {}

func (x *SessionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCommand.ProtoReflect.Descriptor instead.
func (*SessionCommand) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *SessionCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SessionCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SessionCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCommandResult) Reset() {
	*x = SessionCommandResult{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCommandResult) ProtoMessage() {}

func (x *SessionCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCommandResult.ProtoReflect.Descriptor instead.
func (*SessionCommandResult) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *SessionCommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SessionCommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SessionCommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ReleaseDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceRequest) Reset() {
	*x = ReleaseDeviceRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceRequest) ProtoMessage() {}

func (x *ReleaseDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceRequest.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *ReleaseDeviceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ReleaseDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceResponse) Reset() {
	*x = ReleaseDeviceResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceResponse) ProtoMessage() {}

func (x *ReleaseDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceResponse.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *ReleaseDeviceResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type SessionForwardData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SessionForwardData_Setup
	//	*SessionForwardData_Data
	Payload       isSessionForwardData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionForwardData) Reset() {
	*x = SessionForwardData{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionForwardData) ProtoMessage() {}

func (x *SessionForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionForwardData.ProtoReflect.Descriptor instead.
func (*SessionForwardData) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *SessionForwardData) GetPayload() isSessionForwardData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SessionForwardData) GetSetup() *SessionForwardSetup {
	if x != nil {
		if x, ok := x.Payload.(*SessionForwardData_Setup); ok {
			return x.Setup
		}
	}
	return nil
}

func (x *SessionForwardData) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SessionForwardData_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isSessionForwardData_Payload interface {
	isSessionForwardData_Payload()
}

type SessionForwardData_Setup struct {
	Setup *SessionForwardSetup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type SessionForwardData_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SessionForwardData_Setup) isSessionForwardData_Payload() {}

func (*SessionForwardData_Data) isSessionForwardData_Payload() {}

type SessionForwardSetup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InitialCommand string                 `protobuf:"bytes,2,opt,name=initial_command,json=initialCommand,proto3" json:"initial_command,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionForwardSetup) Reset() {
	*x = SessionForwardSetup{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionForwardSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionForwardSetup) ProtoMessage() {}

func (x *SessionForwardSetup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionForwardSetup.ProtoReflect.Descriptor instead.
func (*SessionForwardSetup) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *SessionForwardSetup) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionForwardSetup) GetInitialCommand() string {
	if x != nil {
		return x.InitialCommand
	}
	return ""
}

type AcquireLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serials       []string               `protobuf:"bytes,1,rep,name=serials,proto3" json:"serials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockRequest) Reset() {
	*x = AcquireLockRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockRequest) ProtoMessage() {}

func (x *AcquireLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockRequest.ProtoReflect.Descriptor instead.
func (*AcquireLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *AcquireLockRequest) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

type AcquireLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Serials       []string               `protobuf:"bytes,2,rep,name=serials,proto3" json:"serials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockResponse) Reset() {
	*x = AcquireLockResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockResponse) ProtoMessage() {}

func (x *AcquireLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockResponse.ProtoReflect.Descriptor instead.
func (*AcquireLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *AcquireLockResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *AcquireLockResponse) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

type ReleaseLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockRequest) Reset() {
	*x = ReleaseLockRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockRequest) ProtoMessage() {}

func (x *ReleaseLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *ReleaseLockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type ReleaseLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockResponse) Reset() {
	*x = ReleaseLockResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockResponse) ProtoMessage() {}

func (x *ReleaseLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{22}
}

func (x *ReleaseLockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type LockHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHeartbeatRequest) Reset() {
	*x = LockHeartbeatRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHeartbeatRequest) ProtoMessage() {}

func (x *LockHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*LockHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{23}
}

func (x *LockHeartbeatRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type LockHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHeartbeatResponse) Reset() {
	*x = LockHeartbeatResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHeartbeatResponse) ProtoMessage() {}

func (x *LockHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*LockHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{24}
}

func (x *LockHeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type ReportDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDevicesRequest) Reset() {
	*x = ReportDevicesRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDevicesRequest) ProtoMessage() {}

func (x *ReportDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDevicesRequest.ProtoReflect.Descriptor instead.
func (*ReportDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{25}
}

func (x *ReportDevicesRequest) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ReportDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDevicesResponse) Reset() {
	*x = ReportDevicesResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDevicesResponse) ProtoMessage() {}

func (x *ReportDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDevicesResponse.ProtoReflect.Descriptor instead.
func (*ReportDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{26}
}

var File_proto_orchestrator_orchestrator_proto protoreflect.FileDescriptor

const file_proto_orchestrator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"%proto/orchestrator/orchestrator.proto\x12\forchestrator\"\x9b\x01\n" +
	"\n" +
	"JobRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12D\n" +
	"\frequirements\x18\x04 \x01(\v2 .orchestrator.DeviceRequirementsR\frequirementsJ\x04\b\x02\x10\x03\"\x82\x01\n" +
	"\x12DeviceRequirements\x12\x17\n" +
	"\amin_sdk\x18\x01 \x01(\x05R\x06minSdk\x12\x17\n" +
	"\amax_sdk\x18\x02 \x01(\x05R\x06maxSdk\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\"\xac\x02\n" +
	"\tJobOutput\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.orchestrator.JobStateR\x05state\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12%\n" +
	"\x0equeue_position\x18\x06 \x01(\x05R\rqueuePosition\x12A\n" +
	"\x0fassigned_device\x18\a \x01(\v2\x18.orchestrator.DeviceInfoR\x0eassignedDevice\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"/\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobIdJ\x04\b\x02\x10\x03\"\xfc\x01\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.orchestrator.JobStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12A\n" +
	"\x0fassigned_device\x18\x05 \x01(\v2\x18.orchestrator.DeviceInfoR\x0eassignedDevice\x12%\n" +
	"\x0equeue_position\x18\x06 \x01(\x05R\rqueuePosition\"\x1a\n" +
	"\x12ListDevicesRequestJ\x04\b\x01\x10\x02\"F\n" +
	"\n" +
	"DeviceList\x128\n" +
	"\asources\x18\x01 \x03(\v2\x1e.orchestrator.DeviceSourceInfoR\asources\"\x95\x01\n" +
	"\x10DeviceSourceInfo\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x122\n" +
	"\adevices\x18\x04 \x03(\v2\x18.orchestrator.DeviceInfoR\adevices\"\x9e\x01\n" +
	"\n" +
	"DeviceInfo\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x10\n" +
	"\x03sdk\x18\x04 \x01(\x05R\x03sdk\x12\x18\n" +
	"\arelease\x18\x05 \x01(\x05R\arelease\x12\x12\n" +
	"\x04busy\x18\x06 \x01(\bR\x04busy\"\r\n" +
	"\vPingRequest\"\xc2\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vqueued_jobs\x18\x02 \x01(\x05R\n" +
	"queuedJobs\x12!\n" +
	"\frunning_jobs\x18\x03 \x01(\x05R\vrunningJobs\x12+\n" +
	"\x11available_devices\x18\x04 \x01(\x05R\x10availableDevices\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\x05R\x0eactiveSessions\"\xb7\x01\n" +
	"\x14AcquireDeviceRequest\x12D\n" +
	"\frequirements\x18\x01 \x01(\v2 .orchestrator.DeviceRequirementsR\frequirements\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x120\n" +
	"\x14idle_timeout_seconds\x18\x03 \x01(\x05R\x12idleTimeoutSeconds\"h\n" +
	"\x15AcquireDeviceResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x06device\x18\x02 \x01(\v2\x18.orchestrator.DeviceInfoR\x06device\"r\n" +
	"\x0eSessionCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"c\n" +
	"\x14SessionCommandResult\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"5\n" +
	"\x14ReleaseDeviceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x15ReleaseDeviceResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"p\n" +
	"\x12SessionForwardData\x129\n" +
	"\x05setup\x18\x01 \x01(\v2!.orchestrator.SessionForwardSetupH\x00R\x05setup\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"]\n" +
	"\x13SessionForwardSetup\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0finitial_command\x18\x02 \x01(\tR\x0einitialCommand\".\n" +
	"\x12AcquireLockRequest\x12\x18\n" +
	"\aserials\x18\x01 \x03(\tR\aserials\"H\n" +
	"\x13AcquireLockResponse\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x18\n" +
	"\aserials\x18\x02 \x03(\tR\aserials\"-\n" +
	"\x12ReleaseLockRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"1\n" +
	"\x13ReleaseLockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"/\n" +
	"\x14LockHeartbeatRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"-\n" +
	"\x15LockHeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\"J\n" +
	"\x14ReportDevicesRequest\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.orchestrator.DeviceInfoR\adevices\"\x17\n" +
	"\x15ReportDevicesResponse*d\n" +
	"\bJobState\x12\x15\n" +
	"\x11JOB_STATE_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\xff\a\n" +
	"\fOrchestrator\x12B\n" +
	"\tSubmitJob\x12\x18.orchestrator.JobRequest\x1a\x17.orchestrator.JobOutput\"\x000\x01\x12I\n" +
	"\fGetJobStatus\x12\x1e.orchestrator.JobStatusRequest\x1a\x17.orchestrator.JobStatus\"\x00\x12K\n" +
	"\vListDevices\x12 .orchestrator.ListDevicesRequest\x1a\x18.orchestrator.DeviceList\"\x00\x12?\n" +
	"\x04Ping\x12\x19.orchestrator.PingRequest\x1a\x1a.orchestrator.PingResponse\"\x00\x12Z\n" +
	"\rAcquireDevice\x12\".orchestrator.AcquireDeviceRequest\x1a#.orchestrator.AcquireDeviceResponse\"\x00\x12X\n" +
	"\x10ExecuteOnSession\x12\x1c.orchestrator.SessionCommand\x1a\".orchestrator.SessionCommandResult\"\x000\x01\x12Z\n" +
	"\rReleaseDevice\x12\".orchestrator.ReleaseDeviceRequest\x1a#.orchestrator.ReleaseDeviceResponse\"\x00\x12\\\n" +
	"\x10ForwardToSession\x12 .orchestrator.SessionForwardData\x1a .orchestrator.SessionForwardData\"\x00(\x010\x01\x12T\n" +
	"\vAcquireLock\x12 .orchestrator.AcquireLockRequest\x1a!.orchestrator.AcquireLockResponse\"\x00\x12T\n" +
	"\vReleaseLock\x12 .orchestrator.ReleaseLockRequest\x1a!.orchestrator.ReleaseLockResponse\"\x00\x12Z\n" +
	"\rLockHeartbeat\x12\".orchestrator.LockHeartbeatRequest\x1a#.orchestrator.LockHeartbeatResponse\"\x00\x12Z\n" +
	"\rReportDevices\x12\".orchestrator.ReportDevicesRequest\x1a#.orchestrator.ReportDevicesResponse\"\x00B.Z,github.com/compscidr/sair/proto/orchestratorb\x06proto3"

var (
	file_proto_orchestrator_orchestrator_proto_rawDescOnce sync.Once
	file_proto_orchestrator_orchestrator_proto_rawDescData []byte
)

func file_proto_orchestrator_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)))
	})
	return file_proto_orchestrator_orchestrator_proto_rawDescData
}

var file_proto_orchestrator_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_orchestrator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_orchestrator_orchestrator_proto_goTypes = []any{
	(JobState)(0),                 // 0: orchestrator.JobState
	(*JobRequest)(nil),            // 1: orchestrator.JobRequest
	(*DeviceRequirements)(nil),    // 2: orchestrator.DeviceRequirements
	(*JobOutput)(nil),             // 3: orchestrator.JobOutput
	(*JobStatusRequest)(nil),      // 4: orchestrator.JobStatusRequest
	(*JobStatus)(nil),             // 5: orchestrator.JobStatus
	(*ListDevicesRequest)(nil),    // 6: orchestrator.ListDevicesRequest
	(*DeviceList)(nil),            // 7: orchestrator.DeviceList
	(*DeviceSourceInfo)(nil),      // 8: orchestrator.DeviceSourceInfo
	(*DeviceInfo)(nil),            // 9: orchestrator.DeviceInfo
	(*PingRequest)(nil),           // 10: orchestrator.PingRequest
	(*PingResponse)(nil),          // 11: orchestrator.PingResponse
	(*AcquireDeviceRequest)(nil),  // 12: orchestrator.AcquireDeviceRequest
	(*AcquireDeviceResponse)(nil), // 13: orchestrator.AcquireDeviceResponse
	(*SessionCommand)(nil),        // 14: orchestrator.SessionCommand
	(*SessionCommandResult)(nil),  // 15: orchestrator.SessionCommandResult
	(*ReleaseDeviceRequest)(nil),  // 16: orchestrator.ReleaseDeviceRequest
	(*ReleaseDeviceResponse)(nil), // 17: orchestrator.ReleaseDeviceResponse
	(*SessionForwardData)(nil),    // 18: orchestrator.SessionForwardData
	(*SessionForwardSetup)(nil),   // 19: orchestrator.SessionForwardSetup
	(*AcquireLockRequest)(nil),    // 20: orchestrator.AcquireLockRequest
	(*AcquireLockResponse)(nil),   // 21: orchestrator.AcquireLockResponse
	(*ReleaseLockRequest)(nil),    // 22: orchestrator.ReleaseLockRequest
	(*ReleaseLockResponse)(nil),   // 23: orchestrator.ReleaseLockResponse
	(*LockHeartbeatRequest)(nil),  // 24: orchestrator.LockHeartbeatRequest
	(*LockHeartbeatResponse)(nil), // 25: orchestrator.LockHeartbeatResponse
	(*ReportDevicesRequest)(nil),  // 26: orchestrator.ReportDevicesRequest
	(*ReportDevicesResponse)(nil), // 27: orchestrator.ReportDevicesResponse
}
var file_proto_orchestrator_orchestrator_proto_depIdxs = []int32{
	2,  // 0: orchestrator.JobRequest.requirements:type_name -> orchestrator.DeviceRequirements
	0,  // 1: orchestrator.JobOutput.state:type_name -> orchestrator.JobState
	9,  // 2: orchestrator.JobOutput.assigned_device:type_name -> orchestrator.DeviceInfo
	0,  // 3: orchestrator.JobStatus.state:type_name -> orchestrator.JobState
	9,  // 4: orchestrator.JobStatus.assigned_device:type_name -> orchestrator.DeviceInfo
	8,  // 5: orchestrator.DeviceList.sources:type_name -> orchestrator.DeviceSourceInfo
	9,  // 6: orchestrator.DeviceSourceInfo.devices:type_name -> orchestrator.DeviceInfo
	2,  // 7: orchestrator.AcquireDeviceRequest.requirements:type_name -> orchestrator.DeviceRequirements
	9,  // 8: orchestrator.AcquireDeviceResponse.device:type_name -> orchestrator.DeviceInfo
	19, // 9: orchestrator.SessionForwardData.setup:type_name -> orchestrator.SessionForwardSetup
	9,  // 10: orchestrator.ReportDevicesRequest.devices:type_name -> orchestrator.DeviceInfo
	1,  // 11: orchestrator.Orchestrator.SubmitJob:input_type -> orchestrator.JobRequest
	4,  // 12: orchestrator.Orchestrator.GetJobStatus:input_type -> orchestrator.JobStatusRequest
	6,  // 13: orchestrator.Orchestrator.ListDevices:input_type -> orchestrator.ListDevicesRequest
	10, // 14: orchestrator.Orchestrator.Ping:input_type -> orchestrator.PingRequest
	12, // 15: orchestrator.Orchestrator.AcquireDevice:input_type -> orchestrator.AcquireDeviceRequest
	14, // 16: orchestrator.Orchestrator.ExecuteOnSession:input_type -> orchestrator.SessionCommand
	16, // 17: orchestrator.Orchestrator.ReleaseDevice:input_type -> orchestrator.ReleaseDeviceRequest
	18, // 18: orchestrator.Orchestrator.ForwardToSession:input_type -> orchestrator.SessionForwardData
	20, // 19: orchestrator.Orchestrator.AcquireLock:input_type -> orchestrator.AcquireLockRequest
	22, // 20: orchestrator.Orchestrator.ReleaseLock:input_type -> orchestrator.ReleaseLockRequest
	24, // 21: orchestrator.Orchestrator.LockHeartbeat:input_type -> orchestrator.LockHeartbeatRequest
	26, // 22: orchestrator.Orchestrator.ReportDevices:input_type -> orchestrator.ReportDevicesRequest
	3,  // 23: orchestrator.Orchestrator.SubmitJob:output_type -> orchestrator.JobOutput
	5,  // 24: orchestrator.Orchestrator.GetJobStatus:output_type -> orchestrator.JobStatus
	7,  // 25: orchestrator.Orchestrator.ListDevices:output_type -> orchestrator.DeviceList
	11, // 26: orchestrator.Orchestrator.Ping:output_type -> orchestrator.PingResponse
	13, // 27: orchestrator.Orchestrator.AcquireDevice:output_type -> orchestrator.AcquireDeviceResponse
	15, // 28: orchestrator.Orchestrator.ExecuteOnSession:output_type -> orchestrator.SessionCommandResult
	17, // 29: orchestrator.Orchestrator.ReleaseDevice:output_type -> orchestrator.ReleaseDeviceResponse
	18, // 30: orchestrator.Orchestrator.ForwardToSession:output_type -> orchestrator.SessionForwardData
	21, // 31: orchestrator.Orchestrator.AcquireLock:output_type -> orchestrator.AcquireLockResponse
	23, // 32: orchestrator.Orchestrator.ReleaseLock:output_type -> orchestrator.ReleaseLockResponse
	25, // 33: orchestrator.Orchestrator.LockHeartbeat:output_type -> orchestrator.LockHeartbeatResponse
	27, // 34: orchestrator.Orchestrator.ReportDevices:output_type -> orchestrator.ReportDevicesResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_orchestrator_proto_init() }
func file_proto_orchestrator_orchestrator_proto_init() {
	if File_proto_orchestrator_orchestrator_proto != nil {
		return
	}
	file_proto_orchestrator_orchestrator_proto_msgTypes[17].OneofWrappers = []any{
		(*SessionForwardData_Setup)(nil),
		(*SessionForwardData_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_orchestrator_proto_depIdxs,
		EnumInfos:         file_proto_orchestrator_orchestrator_proto_enumTypes,
		MessageInfos:      file_proto_orchestrator_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_orchestrator_proto = out.File
	file_proto_orchestrator_orchestrator_proto_goTypes = nil
	file_proto_orchestrator_orchestrator_proto_depIdxs = nil
}
