// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/orchestrator/orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelSide int32

const (
	TunnelSide_TUNNEL_SIDE_UNSPECIFIED TunnelSide = 0
	TunnelSide_TUNNEL_SIDE_HOLDER      TunnelSide = 1 // has the lock and the ADB client
	TunnelSide_TUNNEL_SIDE_OWNER       TunnelSide = 2 // has the device
)

// Enum value maps for TunnelSide.
var (
	TunnelSide_name = map[int32]string{
		0: "TUNNEL_SIDE_UNSPECIFIED",
		1: "TUNNEL_SIDE_HOLDER",
		2: "TUNNEL_SIDE_OWNER",
	}
	TunnelSide_value = map[string]int32{
		"TUNNEL_SIDE_UNSPECIFIED": 0,
		"TUNNEL_SIDE_HOLDER":      1,
		"TUNNEL_SIDE_OWNER":       2,
	}
)

func (x TunnelSide) Enum() *TunnelSide {
	p := new(TunnelSide)
	*p = x
	return p
}

func (x TunnelSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelSide) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestrator_orchestrator_proto_enumTypes[0].Descriptor()
}

func (TunnelSide) Type() protoreflect.EnumType {
	return &file_proto_orchestrator_orchestrator_proto_enumTypes[0]
}

func (x TunnelSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelSide.Descriptor instead.
func (TunnelSide) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*DeviceSourceInfo    `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceList) GetSources() []*DeviceSourceInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

type DeviceSourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Devices       []*DeviceInfo          `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSourceInfo) Reset() {
	*x = DeviceSourceInfo{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSourceInfo) ProtoMessage() {}

func (x *DeviceSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSourceInfo.ProtoReflect.Descriptor instead.
func (*DeviceSourceInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceSourceInfo) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DeviceSourceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeviceSourceInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DeviceSourceInfo) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Sdk           int32                  `protobuf:"varint,4,opt,name=sdk,proto3" json:"sdk,omitempty"`
	Release       int32                  `protobuf:"varint,5,opt,name=release,proto3" json:"release,omitempty"`
	Busy          bool                   `protobuf:"varint,6,opt,name=busy,proto3" json:"busy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetSdk() int32 {
	if x != nil {
		return x.Sdk
	}
	return 0
}

func (x *DeviceInfo) GetRelease() int32 {
	if x != nil {
		return x.Release
	}
	return 0
}

func (x *DeviceInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

// A lock request either names the devices it wants (serials) or asks for a
// number of arbitrary free devices (count). Setting both is invalid; setting
// neither means "all devices in the tenant's pool".
type AcquireLockRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Serials []string               `protobuf:"bytes,1,rep,name=serials,proto3" json:"serials,omitempty"`
	Repo    string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Count   int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// Link to the CI run holding the lock (e.g. a GitHub Actions run URL).
	RunUrl string `protobuf:"bytes,4,opt,name=run_url,json=runUrl,proto3" json:"run_url,omitempty"`
	// Same value as ProxyHello.proxy_id. Locks are granted only on devices this
	// proxy reported. Empty from proxies that predate sessions.
	ProxyId string `protobuf:"bytes,6,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	// Queue order when the devices are busy: higher is served first, ties are
	// FIFO. 0 (the default) is what every request had before this field.
	Priority      int32 `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockRequest) Reset() {
	*x = AcquireLockRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockRequest) ProtoMessage() {}

func (x *AcquireLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockRequest.ProtoReflect.Descriptor instead.
func (*AcquireLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *AcquireLockRequest) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

func (x *AcquireLockRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *AcquireLockRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AcquireLockRequest) GetRunUrl() string {
	if x != nil {
		return x.RunUrl
	}
	return ""
}

func (x *AcquireLockRequest) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *AcquireLockRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type AcquireLockResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	LockId  string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Serials []string               `protobuf:"bytes,2,rep,name=serials,proto3" json:"serials,omitempty"`
	// Granted devices that live on another proxy (or another tenant): reach them
	// through Tunnel rather than a local device source. Carries the owner's
	// reported info so the holder can list them. Empty for proxies without a
	// proxy_id and from orchestrators that predate the relay.
	RemoteDevices []*DeviceInfo `protobuf:"bytes,3,rep,name=remote_devices,json=remoteDevices,proto3" json:"remote_devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockResponse) Reset() {
	*x = AcquireLockResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockResponse) ProtoMessage() {}

func (x *AcquireLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockResponse.ProtoReflect.Descriptor instead.
func (*AcquireLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *AcquireLockResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *AcquireLockResponse) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

func (x *AcquireLockResponse) GetRemoteDevices() []*DeviceInfo {
	if x != nil {
		return x.RemoteDevices
	}
	return nil
}

// One ADB request a client made on a scoped port while holding a lock, as
// observed by the proxy: the service string the client asked the device for
// (e.g. "shell,v2,raw:am instrument -w ..."), when, how long the tunnel stayed
// open, and how many bytes came back. Together these are the job's log.
//
// A request is reported in pieces that share a request_id: an open entry when
// the service is seen (timestamp, serial, service, open = true), zero or more
// output entries as the device answers (output set, nothing else), and a close
// entry when the tunnel ends (duration_ms, bytes_to_client, plus serial and
// service again). Proxies that predate this send one entry per request, the
// close, with request_id 0.
type LockLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	BytesToClient int64                  `protobuf:"varint,5,opt,name=bytes_to_client,json=bytesToClient,proto3" json:"bytes_to_client,omitempty"`
	RequestId     uint64                 `protobuf:"varint,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Open          bool                   `protobuf:"varint,7,opt,name=open,proto3" json:"open,omitempty"`
	// Text the device sent back, in order, for shell services only; sync,
	// exec and the rest are binary and only counted. Non-UTF-8 output is
	// replaced by a single "(binary output omitted)" piece.
	Output        string `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockLogEntry) Reset() {
	*x = LockLogEntry{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockLogEntry) ProtoMessage() {}

func (x *LockLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockLogEntry.ProtoReflect.Descriptor instead.
func (*LockLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *LockLogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LockLogEntry) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *LockLogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LockLogEntry) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *LockLogEntry) GetBytesToClient() int64 {
	if x != nil {
		return x.BytesToClient
	}
	return 0
}

func (x *LockLogEntry) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *LockLogEntry) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *LockLogEntry) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ReleaseLockRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	LockId string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	// Outcome of the job that held the lock. From the client: success,
	// failure, cancelled, or empty when it did not say. From the proxy itself:
	// error (scoped port setup failed) or cancelled (proxy shut down). Locks
	// that expire without a release are recorded by the orchestrator as timeout.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Log entries not yet sent by a heartbeat.
	Log           []*LockLogEntry `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockRequest) Reset() {
	*x = ReleaseLockRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockRequest) ProtoMessage() {}

func (x *ReleaseLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseLockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *ReleaseLockRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReleaseLockRequest) GetLog() []*LockLogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

type ReleaseLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockResponse) Reset() {
	*x = ReleaseLockResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockResponse) ProtoMessage() {}

func (x *ReleaseLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseLockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type LockHeartbeatRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	LockId string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	// Log entries recorded since the previous heartbeat, so a lock that later
	// expires still has its history on the orchestrator.
	Log           []*LockLogEntry `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHeartbeatRequest) Reset() {
	*x = LockHeartbeatRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHeartbeatRequest) ProtoMessage() {}

func (x *LockHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*LockHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *LockHeartbeatRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *LockHeartbeatRequest) GetLog() []*LockLogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

type LockHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHeartbeatResponse) Reset() {
	*x = LockHeartbeatResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHeartbeatResponse) ProtoMessage() {}

func (x *LockHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*LockHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *LockHeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

// ReportDevicesRequest is sent by the proxy to report its current device list.
// The busy field in DeviceInfo is ignored; busy state is managed by the orchestrator.
type ReportDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDevicesRequest) Reset() {
	*x = ReportDevicesRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDevicesRequest) ProtoMessage() {}

func (x *ReportDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDevicesRequest.ProtoReflect.Descriptor instead.
func (*ReportDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *ReportDevicesRequest) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ReportDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDevicesResponse) Reset() {
	*x = ReportDevicesResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDevicesResponse) ProtoMessage() {}

func (x *ReportDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDevicesResponse.ProtoReflect.Descriptor instead.
func (*ReportDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{12}
}

// Proxy -> orchestrator envelope. hello is always the first message.
type ProxyMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ProxyMessage_Hello
	//	*ProxyMessage_Devices
	//	*ProxyMessage_LockLog
	//	*ProxyMessage_Heartbeat
	//	*ProxyMessage_RelayFailed
	Msg           isProxyMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyMessage) Reset() {
	*x = ProxyMessage{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMessage) ProtoMessage() {}

func (x *ProxyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMessage.ProtoReflect.Descriptor instead.
func (*ProxyMessage) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *ProxyMessage) GetMsg() isProxyMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ProxyMessage) GetHello() *ProxyHello {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ProxyMessage) GetDevices() *ReportDevicesRequest {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMessage_Devices); ok {
			return x.Devices
		}
	}
	return nil
}

func (x *ProxyMessage) GetLockLog() *LockLog {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMessage_LockLog); ok {
			return x.LockLog
		}
	}
	return nil
}

func (x *ProxyMessage) GetHeartbeat() *LockHeartbeatRequest {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ProxyMessage) GetRelayFailed() *RelayFailed {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMessage_RelayFailed); ok {
			return x.RelayFailed
		}
	}
	return nil
}

type isProxyMessage_Msg interface {
	isProxyMessage_Msg()
}

type ProxyMessage_Hello struct {
	Hello *ProxyHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ProxyMessage_Devices struct {
	Devices *ReportDevicesRequest `protobuf:"bytes,2,opt,name=devices,proto3,oneof"` // full list, same semantics as the unary call
}

type ProxyMessage_LockLog struct {
	LockLog *LockLog `protobuf:"bytes,3,opt,name=lock_log,json=lockLog,proto3,oneof"`
}

type ProxyMessage_Heartbeat struct {
	Heartbeat *LockHeartbeatRequest `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"` // its log field is left empty on the stream
}

type ProxyMessage_RelayFailed struct {
	RelayFailed *RelayFailed `protobuf:"bytes,5,opt,name=relay_failed,json=relayFailed,proto3,oneof"`
}

func (*ProxyMessage_Hello) isProxyMessage_Msg() {}

func (*ProxyMessage_Devices) isProxyMessage_Msg() {}

func (*ProxyMessage_LockLog) isProxyMessage_Msg() {}

func (*ProxyMessage_Heartbeat) isProxyMessage_Msg() {}

func (*ProxyMessage_RelayFailed) isProxyMessage_Msg() {}

type ProxyHello struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Version                string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                                  // internal/version.Version, "dev" for local builds
	ProxyId                string                 `protobuf:"bytes,2,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`                                                   // hostname by default, PROXY_ID env overrides
	DeviceReportIntervalS  int64                  `protobuf:"varint,3,opt,name=device_report_interval_s,json=deviceReportIntervalS,proto3" json:"device_report_interval_s,omitempty"`    // informational
	LockHeartbeatIntervalS int64                  `protobuf:"varint,4,opt,name=lock_heartbeat_interval_s,json=lockHeartbeatIntervalS,proto3" json:"lock_heartbeat_interval_s,omitempty"` // informational
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProxyHello) Reset() {
	*x = ProxyHello{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHello) ProtoMessage() {}

func (x *ProxyHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHello.ProtoReflect.Descriptor instead.
func (*ProxyHello) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *ProxyHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProxyHello) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyHello) GetDeviceReportIntervalS() int64 {
	if x != nil {
		return x.DeviceReportIntervalS
	}
	return 0
}

func (x *ProxyHello) GetLockHeartbeatIntervalS() int64 {
	if x != nil {
		return x.LockHeartbeatIntervalS
	}
	return 0
}

type LockLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Entries       []*LockLogEntry        `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockLog) Reset() {
	*x = LockLog{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockLog) ProtoMessage() {}

func (x *LockLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockLog.ProtoReflect.Descriptor instead.
func (*LockLog) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *LockLog) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *LockLog) GetEntries() []*LockLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Orchestrator -> proxy envelope.
type OrchestratorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*OrchestratorMessage_Welcome
	//	*OrchestratorMessage_LockExpired
	//	*OrchestratorMessage_RelayOpen
	Msg           isOrchestratorMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorMessage) Reset() {
	*x = OrchestratorMessage{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage) ProtoMessage() {}

func (x *OrchestratorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *OrchestratorMessage) GetMsg() isOrchestratorMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *OrchestratorMessage) GetWelcome() *OrchestratorWelcome {
	if x != nil {
		if x, ok := x.Msg.(*OrchestratorMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetLockExpired() *LockExpired {
	if x != nil {
		if x, ok := x.Msg.(*OrchestratorMessage_LockExpired); ok {
			return x.LockExpired
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetRelayOpen() *RelayOpen {
	if x != nil {
		if x, ok := x.Msg.(*OrchestratorMessage_RelayOpen); ok {
			return x.RelayOpen
		}
	}
	return nil
}

type isOrchestratorMessage_Msg interface {
	isOrchestratorMessage_Msg()
}

type OrchestratorMessage_Welcome struct {
	Welcome *OrchestratorWelcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type OrchestratorMessage_LockExpired struct {
	LockExpired *LockExpired `protobuf:"bytes,2,opt,name=lock_expired,json=lockExpired,proto3,oneof"`
}

type OrchestratorMessage_RelayOpen struct {
	RelayOpen *RelayOpen `protobuf:"bytes,3,opt,name=relay_open,json=relayOpen,proto3,oneof"`
}

func (*OrchestratorMessage_Welcome) isOrchestratorMessage_Msg() {}

func (*OrchestratorMessage_LockExpired) isOrchestratorMessage_Msg() {}

func (*OrchestratorMessage_RelayOpen) isOrchestratorMessage_Msg() {}

type OrchestratorWelcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                   // orchestrator build commit
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // which account the proxy landed in
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorWelcome) Reset() {
	*x = OrchestratorWelcome{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorWelcome) ProtoMessage() {}

func (x *OrchestratorWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorWelcome.ProtoReflect.Descriptor instead.
func (*OrchestratorWelcome) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *OrchestratorWelcome) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OrchestratorWelcome) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type LockExpired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockExpired) Reset() {
	*x = LockExpired{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockExpired) ProtoMessage() {}

func (x *LockExpired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockExpired.ProtoReflect.Descriptor instead.
func (*LockExpired) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *LockExpired) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

// Tunnel payload: setup first from each side, then raw ADB bytes (the same
// shape as devicesource.ForwardData, so the owner can pump without translating).
//
// half_close is a TCP-style "I'm done writing" signal for the *other* leg of
// the tunnel. gRPC's own CloseSend only tells the orchestrator "no more from
// me on this call" -- the orchestrator, splicing two independent Tunnel
// calls, has no transport-level way to make the peer's own call observe that
// without ending it outright, which would also cut off any reply still in
// flight (e.g. a device finishing its output after stdin closes). Carrying
// it as an explicit message lets the orchestrator forward it while keeping
// both calls open for the reply.
type TunnelData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelData_Setup
	//	*TunnelData_Data
	//	*TunnelData_HalfClose
	//	*TunnelData_Accepted
	Payload       isTunnelData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *TunnelData) GetPayload() isTunnelData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelData) GetSetup() *TunnelSetup {
	if x != nil {
		if x, ok := x.Payload.(*TunnelData_Setup); ok {
			return x.Setup
		}
	}
	return nil
}

func (x *TunnelData) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TunnelData_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelData) GetHalfClose() bool {
	if x != nil {
		if x, ok := x.Payload.(*TunnelData_HalfClose); ok {
			return x.HalfClose
		}
	}
	return false
}

func (x *TunnelData) GetAccepted() bool {
	if x != nil {
		if x, ok := x.Payload.(*TunnelData_Accepted); ok {
			return x.Accepted
		}
	}
	return false
}

type isTunnelData_Payload interface {
	isTunnelData_Payload()
}

type TunnelData_Setup struct {
	Setup *TunnelSetup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type TunnelData_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type TunnelData_HalfClose struct {
	HalfClose bool `protobuf:"varint,3,opt,name=half_close,json=halfClose,proto3,oneof"`
}

type TunnelData_Accepted struct {
	// orchestrator -> holder only: the owner joined, bytes may flow
	Accepted bool `protobuf:"varint,4,opt,name=accepted,proto3,oneof"`
}

func (*TunnelData_Setup) isTunnelData_Payload() {}

func (*TunnelData_Data) isTunnelData_Payload() {}

func (*TunnelData_HalfClose) isTunnelData_Payload() {}

func (*TunnelData_Accepted) isTunnelData_Payload() {}

type TunnelSetup struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TunnelId string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Side     TunnelSide             `protobuf:"varint,2,opt,name=side,proto3,enum=orchestrator.TunnelSide" json:"side,omitempty"`
	// HOLDER only: what the ADB client asked for, so the owner opens the device
	// with the same initial command. Empty for a plain transport.
	Serial         string `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	InitialCommand string `protobuf:"bytes,4,opt,name=initial_command,json=initialCommand,proto3" json:"initial_command,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TunnelSetup) Reset() {
	*x = TunnelSetup{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelSetup) ProtoMessage() {}

func (x *TunnelSetup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelSetup.ProtoReflect.Descriptor instead.
func (*TunnelSetup) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *TunnelSetup) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelSetup) GetSide() TunnelSide {
	if x != nil {
		return x.Side
	}
	return TunnelSide_TUNNEL_SIDE_UNSPECIFIED
}

func (x *TunnelSetup) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *TunnelSetup) GetInitialCommand() string {
	if x != nil {
		return x.InitialCommand
	}
	return ""
}

// Orchestrator -> owner proxy: open your half of tunnel_id for this device.
type RelayOpen struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TunnelId       string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Serial         string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`                                       // as the owner knows it
	InitialCommand string                 `protobuf:"bytes,3,opt,name=initial_command,json=initialCommand,proto3" json:"initial_command,omitempty"` // forwarded from the holder's setup
	LockId         string                 `protobuf:"bytes,4,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`                         // for logging
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelayOpen) Reset() {
	*x = RelayOpen{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayOpen) ProtoMessage() {}

func (x *RelayOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayOpen.ProtoReflect.Descriptor instead.
func (*RelayOpen) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *RelayOpen) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RelayOpen) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RelayOpen) GetInitialCommand() string {
	if x != nil {
		return x.InitialCommand
	}
	return ""
}

func (x *RelayOpen) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

// Owner proxy -> orchestrator: could not open the device; the holder's ADB
// client gets a FAIL with this text.
type RelayFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayFailed) Reset() {
	*x = RelayFailed{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayFailed) ProtoMessage() {}

func (x *RelayFailed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayFailed.ProtoReflect.Descriptor instead.
func (*RelayFailed) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{22}
}

func (x *RelayFailed) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RelayFailed) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_orchestrator_orchestrator_proto protoreflect.FileDescriptor

const file_proto_orchestrator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"%proto/orchestrator/orchestrator.proto\x12\forchestrator\"\x1a\n" +
	"\x12ListDevicesRequestJ\x04\b\x01\x10\x02\"F\n" +
	"\n" +
	"DeviceList\x128\n" +
	"\asources\x18\x01 \x03(\v2\x1e.orchestrator.DeviceSourceInfoR\asources\"\x95\x01\n" +
	"\x10DeviceSourceInfo\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x122\n" +
	"\adevices\x18\x04 \x03(\v2\x18.orchestrator.DeviceInfoR\adevices\"\x9e\x01\n" +
	"\n" +
	"DeviceInfo\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x10\n" +
	"\x03sdk\x18\x04 \x01(\x05R\x03sdk\x12\x18\n" +
	"\arelease\x18\x05 \x01(\x05R\arelease\x12\x12\n" +
	"\x04busy\x18\x06 \x01(\bR\x04busy\"\xa8\x01\n" +
	"\x12AcquireLockRequest\x12\x18\n" +
	"\aserials\x18\x01 \x03(\tR\aserials\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x17\n" +
	"\arun_url\x18\x04 \x01(\tR\x06runUrl\x12\x19\n" +
	"\bproxy_id\x18\x06 \x01(\tR\aproxyId\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"\x89\x01\n" +
	"\x13AcquireLockResponse\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x18\n" +
	"\aserials\x18\x02 \x03(\tR\aserials\x12?\n" +
	"\x0eremote_devices\x18\x03 \x03(\v2\x18.orchestrator.DeviceInfoR\rremoteDevices\"\xf7\x01\n" +
	"\fLockLogEntry\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12&\n" +
	"\x0fbytes_to_client\x18\x05 \x01(\x03R\rbytesToClient\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\x04R\trequestId\x12\x12\n" +
	"\x04open\x18\a \x01(\bR\x04open\x12\x16\n" +
	"\x06output\x18\b \x01(\tR\x06output\"s\n" +
	"\x12ReleaseLockRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x03log\x18\x03 \x03(\v2\x1a.orchestrator.LockLogEntryR\x03log\"1\n" +
	"\x13ReleaseLockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"]\n" +
	"\x14LockHeartbeatRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12,\n" +
	"\x03log\x18\x02 \x03(\v2\x1a.orchestrator.LockLogEntryR\x03log\"-\n" +
	"\x15LockHeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\"J\n" +
	"\x14ReportDevicesRequest\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.orchestrator.DeviceInfoR\adevices\"\x17\n" +
	"\x15ReportDevicesResponse\"\xbf\x02\n" +
	"\fProxyMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.orchestrator.ProxyHelloH\x00R\x05hello\x12>\n" +
	"\adevices\x18\x02 \x01(\v2\".orchestrator.ReportDevicesRequestH\x00R\adevices\x122\n" +
	"\block_log\x18\x03 \x01(\v2\x15.orchestrator.LockLogH\x00R\alockLog\x12B\n" +
	"\theartbeat\x18\x04 \x01(\v2\".orchestrator.LockHeartbeatRequestH\x00R\theartbeat\x12>\n" +
	"\frelay_failed\x18\x05 \x01(\v2\x19.orchestrator.RelayFailedH\x00R\vrelayFailedB\x05\n" +
	"\x03msg\"\xb5\x01\n" +
	"\n" +
	"ProxyHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\bproxy_id\x18\x02 \x01(\tR\aproxyId\x127\n" +
	"\x18device_report_interval_s\x18\x03 \x01(\x03R\x15deviceReportIntervalS\x129\n" +
	"\x19lock_heartbeat_interval_s\x18\x04 \x01(\x03R\x16lockHeartbeatIntervalS\"X\n" +
	"\aLockLog\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x124\n" +
	"\aentries\x18\x02 \x03(\v2\x1a.orchestrator.LockLogEntryR\aentries\"\xd5\x01\n" +
	"\x13OrchestratorMessage\x12=\n" +
	"\awelcome\x18\x01 \x01(\v2!.orchestrator.OrchestratorWelcomeH\x00R\awelcome\x12>\n" +
	"\flock_expired\x18\x02 \x01(\v2\x19.orchestrator.LockExpiredH\x00R\vlockExpired\x128\n" +
	"\n" +
	"relay_open\x18\x03 \x01(\v2\x17.orchestrator.RelayOpenH\x00R\trelayOpenB\x05\n" +
	"\x03msg\"L\n" +
	"\x13OrchestratorWelcome\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"&\n" +
	"\vLockExpired\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"\x9f\x01\n" +
	"\n" +
	"TunnelData\x121\n" +
	"\x05setup\x18\x01 \x01(\v2\x19.orchestrator.TunnelSetupH\x00R\x05setup\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x1f\n" +
	"\n" +
	"half_close\x18\x03 \x01(\bH\x00R\thalfClose\x12\x1c\n" +
	"\baccepted\x18\x04 \x01(\bH\x00R\bacceptedB\t\n" +
	"\apayload\"\x99\x01\n" +
	"\vTunnelSetup\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12,\n" +
	"\x04side\x18\x02 \x01(\x0e2\x18.orchestrator.TunnelSideR\x04side\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12'\n" +
	"\x0finitial_command\x18\x04 \x01(\tR\x0einitialCommand\"\x82\x01\n" +
	"\tRelayOpen\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12'\n" +
	"\x0finitial_command\x18\x03 \x01(\tR\x0einitialCommand\x12\x17\n" +
	"\alock_id\x18\x04 \x01(\tR\x06lockId\"@\n" +
	"\vRelayFailed\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*X\n" +
	"\n" +
	"TunnelSide\x12\x1b\n" +
	"\x17TUNNEL_SIDE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TUNNEL_SIDE_HOLDER\x10\x01\x12\x15\n" +
	"\x11TUNNEL_SIDE_OWNER\x10\x022\xd3\x04\n" +
	"\fOrchestrator\x12K\n" +
	"\vListDevices\x12 .orchestrator.ListDevicesRequest\x1a\x18.orchestrator.DeviceList\"\x00\x12T\n" +
	"\vAcquireLock\x12 .orchestrator.AcquireLockRequest\x1a!.orchestrator.AcquireLockResponse\"\x00\x12T\n" +
	"\vReleaseLock\x12 .orchestrator.ReleaseLockRequest\x1a!.orchestrator.ReleaseLockResponse\"\x00\x12Z\n" +
	"\rLockHeartbeat\x12\".orchestrator.LockHeartbeatRequest\x1a#.orchestrator.LockHeartbeatResponse\"\x00\x12Z\n" +
	"\rReportDevices\x12\".orchestrator.ReportDevicesRequest\x1a#.orchestrator.ReportDevicesResponse\"\x00\x12N\n" +
	"\aSession\x12\x1a.orchestrator.ProxyMessage\x1a!.orchestrator.OrchestratorMessage\"\x00(\x010\x01\x12B\n" +
	"\x06Tunnel\x12\x18.orchestrator.TunnelData\x1a\x18.orchestrator.TunnelData\"\x00(\x010\x01B.Z,github.com/compscidr/sair/proto/orchestratorb\x06proto3"

var (
	file_proto_orchestrator_orchestrator_proto_rawDescOnce sync.Once
	file_proto_orchestrator_orchestrator_proto_rawDescData []byte
)

func file_proto_orchestrator_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)))
	})
	return file_proto_orchestrator_orchestrator_proto_rawDescData
}

var file_proto_orchestrator_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_orchestrator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_orchestrator_orchestrator_proto_goTypes = []any{
	(TunnelSide)(0),               // 0: orchestrator.TunnelSide
	(*ListDevicesRequest)(nil),    // 1: orchestrator.ListDevicesRequest
	(*DeviceList)(nil),            // 2: orchestrator.DeviceList
	(*DeviceSourceInfo)(nil),      // 3: orchestrator.DeviceSourceInfo
	(*DeviceInfo)(nil),            // 4: orchestrator.DeviceInfo
	(*AcquireLockRequest)(nil),    // 5: orchestrator.AcquireLockRequest
	(*AcquireLockResponse)(nil),   // 6: orchestrator.AcquireLockResponse
	(*LockLogEntry)(nil),          // 7: orchestrator.LockLogEntry
	(*ReleaseLockRequest)(nil),    // 8: orchestrator.ReleaseLockRequest
	(*ReleaseLockResponse)(nil),   // 9: orchestrator.ReleaseLockResponse
	(*LockHeartbeatRequest)(nil),  // 10: orchestrator.LockHeartbeatRequest
	(*LockHeartbeatResponse)(nil), // 11: orchestrator.LockHeartbeatResponse
	(*ReportDevicesRequest)(nil),  // 12: orchestrator.ReportDevicesRequest
	(*ReportDevicesResponse)(nil), // 13: orchestrator.ReportDevicesResponse
	(*ProxyMessage)(nil),          // 14: orchestrator.ProxyMessage
	(*ProxyHello)(nil),            // 15: orchestrator.ProxyHello
	(*LockLog)(nil),               // 16: orchestrator.LockLog
	(*OrchestratorMessage)(nil),   // 17: orchestrator.OrchestratorMessage
	(*OrchestratorWelcome)(nil),   // 18: orchestrator.OrchestratorWelcome
	(*LockExpired)(nil),           // 19: orchestrator.LockExpired
	(*TunnelData)(nil),            // 20: orchestrator.TunnelData
	(*TunnelSetup)(nil),           // 21: orchestrator.TunnelSetup
	(*RelayOpen)(nil),             // 22: orchestrator.RelayOpen
	(*RelayFailed)(nil),           // 23: orchestrator.RelayFailed
}
var file_proto_orchestrator_orchestrator_proto_depIdxs = []int32{
	3,  // 0: orchestrator.DeviceList.sources:type_name -> orchestrator.DeviceSourceInfo
	4,  // 1: orchestrator.DeviceSourceInfo.devices:type_name -> orchestrator.DeviceInfo
	4,  // 2: orchestrator.AcquireLockResponse.remote_devices:type_name -> orchestrator.DeviceInfo
	7,  // 3: orchestrator.ReleaseLockRequest.log:type_name -> orchestrator.LockLogEntry
	7,  // 4: orchestrator.LockHeartbeatRequest.log:type_name -> orchestrator.LockLogEntry
	4,  // 5: orchestrator.ReportDevicesRequest.devices:type_name -> orchestrator.DeviceInfo
	15, // 6: orchestrator.ProxyMessage.hello:type_name -> orchestrator.ProxyHello
	12, // 7: orchestrator.ProxyMessage.devices:type_name -> orchestrator.ReportDevicesRequest
	16, // 8: orchestrator.ProxyMessage.lock_log:type_name -> orchestrator.LockLog
	10, // 9: orchestrator.ProxyMessage.heartbeat:type_name -> orchestrator.LockHeartbeatRequest
	23, // 10: orchestrator.ProxyMessage.relay_failed:type_name -> orchestrator.RelayFailed
	7,  // 11: orchestrator.LockLog.entries:type_name -> orchestrator.LockLogEntry
	18, // 12: orchestrator.OrchestratorMessage.welcome:type_name -> orchestrator.OrchestratorWelcome
	19, // 13: orchestrator.OrchestratorMessage.lock_expired:type_name -> orchestrator.LockExpired
	22, // 14: orchestrator.OrchestratorMessage.relay_open:type_name -> orchestrator.RelayOpen
	21, // 15: orchestrator.TunnelData.setup:type_name -> orchestrator.TunnelSetup
	0,  // 16: orchestrator.TunnelSetup.side:type_name -> orchestrator.TunnelSide
	1,  // 17: orchestrator.Orchestrator.ListDevices:input_type -> orchestrator.ListDevicesRequest
	5,  // 18: orchestrator.Orchestrator.AcquireLock:input_type -> orchestrator.AcquireLockRequest
	8,  // 19: orchestrator.Orchestrator.ReleaseLock:input_type -> orchestrator.ReleaseLockRequest
	10, // 20: orchestrator.Orchestrator.LockHeartbeat:input_type -> orchestrator.LockHeartbeatRequest
	12, // 21: orchestrator.Orchestrator.ReportDevices:input_type -> orchestrator.ReportDevicesRequest
	14, // 22: orchestrator.Orchestrator.Session:input_type -> orchestrator.ProxyMessage
	20, // 23: orchestrator.Orchestrator.Tunnel:input_type -> orchestrator.TunnelData
	2,  // 24: orchestrator.Orchestrator.ListDevices:output_type -> orchestrator.DeviceList
	6,  // 25: orchestrator.Orchestrator.AcquireLock:output_type -> orchestrator.AcquireLockResponse
	9,  // 26: orchestrator.Orchestrator.ReleaseLock:output_type -> orchestrator.ReleaseLockResponse
	11, // 27: orchestrator.Orchestrator.LockHeartbeat:output_type -> orchestrator.LockHeartbeatResponse
	13, // 28: orchestrator.Orchestrator.ReportDevices:output_type -> orchestrator.ReportDevicesResponse
	17, // 29: orchestrator.Orchestrator.Session:output_type -> orchestrator.OrchestratorMessage
	20, // 30: orchestrator.Orchestrator.Tunnel:output_type -> orchestrator.TunnelData
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_orchestrator_proto_init() }
func file_proto_orchestrator_orchestrator_proto_init() {
	if File_proto_orchestrator_orchestrator_proto != nil {
		return
	}
	file_proto_orchestrator_orchestrator_proto_msgTypes[13].OneofWrappers = []any{
		(*ProxyMessage_Hello)(nil),
		(*ProxyMessage_Devices)(nil),
		(*ProxyMessage_LockLog)(nil),
		(*ProxyMessage_Heartbeat)(nil),
		(*ProxyMessage_RelayFailed)(nil),
	}
	file_proto_orchestrator_orchestrator_proto_msgTypes[16].OneofWrappers = []any{
		(*OrchestratorMessage_Welcome)(nil),
		(*OrchestratorMessage_LockExpired)(nil),
		(*OrchestratorMessage_RelayOpen)(nil),
	}
	file_proto_orchestrator_orchestrator_proto_msgTypes[19].OneofWrappers = []any{
		(*TunnelData_Setup)(nil),
		(*TunnelData_Data)(nil),
		(*TunnelData_HalfClose)(nil),
		(*TunnelData_Accepted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_orchestrator_proto_depIdxs,
		EnumInfos:         file_proto_orchestrator_orchestrator_proto_enumTypes,
		MessageInfos:      file_proto_orchestrator_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_orchestrator_proto = out.File
	file_proto_orchestrator_orchestrator_proto_goTypes = nil
	file_proto_orchestrator_orchestrator_proto_depIdxs = nil
}
