// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/orchestrator/orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*DeviceSourceInfo    `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceList) GetSources() []*DeviceSourceInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

type DeviceSourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Devices       []*DeviceInfo          `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSourceInfo) Reset() {
	*x = DeviceSourceInfo{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSourceInfo) ProtoMessage() {}

func (x *DeviceSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSourceInfo.ProtoReflect.Descriptor instead.
func (*DeviceSourceInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceSourceInfo) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DeviceSourceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeviceSourceInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DeviceSourceInfo) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Sdk           int32                  `protobuf:"varint,4,opt,name=sdk,proto3" json:"sdk,omitempty"`
	Release       int32                  `protobuf:"varint,5,opt,name=release,proto3" json:"release,omitempty"`
	Busy          bool                   `protobuf:"varint,6,opt,name=busy,proto3" json:"busy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetSdk() int32 {
	if x != nil {
		return x.Sdk
	}
	return 0
}

func (x *DeviceInfo) GetRelease() int32 {
	if x != nil {
		return x.Release
	}
	return 0
}

func (x *DeviceInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

type AcquireLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serials       []string               `protobuf:"bytes,1,rep,name=serials,proto3" json:"serials,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockRequest) Reset() {
	*x = AcquireLockRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockRequest) ProtoMessage() {}

func (x *AcquireLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockRequest.ProtoReflect.Descriptor instead.
func (*AcquireLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *AcquireLockRequest) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

func (x *AcquireLockRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type AcquireLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Serials       []string               `protobuf:"bytes,2,rep,name=serials,proto3" json:"serials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockResponse) Reset() {
	*x = AcquireLockResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockResponse) ProtoMessage() {}

func (x *AcquireLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockResponse.ProtoReflect.Descriptor instead.
func (*AcquireLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *AcquireLockResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *AcquireLockResponse) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

type ReleaseLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockRequest) Reset() {
	*x = ReleaseLockRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockRequest) ProtoMessage() {}

func (x *ReleaseLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseLockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type ReleaseLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockResponse) Reset() {
	*x = ReleaseLockResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockResponse) ProtoMessage() {}

func (x *ReleaseLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseLockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type LockHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHeartbeatRequest) Reset() {
	*x = LockHeartbeatRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHeartbeatRequest) ProtoMessage() {}

func (x *LockHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*LockHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *LockHeartbeatRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type LockHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHeartbeatResponse) Reset() {
	*x = LockHeartbeatResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHeartbeatResponse) ProtoMessage() {}

func (x *LockHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*LockHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *LockHeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

// ReportDevicesRequest is sent by the proxy to report its current device list.
// The busy field in DeviceInfo is ignored; busy state is managed by the orchestrator.
type ReportDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDevicesRequest) Reset() {
	*x = ReportDevicesRequest{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDevicesRequest) ProtoMessage() {}

func (x *ReportDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDevicesRequest.ProtoReflect.Descriptor instead.
func (*ReportDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *ReportDevicesRequest) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ReportDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDevicesResponse) Reset() {
	*x = ReportDevicesResponse{}
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDevicesResponse) ProtoMessage() {}

func (x *ReportDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDevicesResponse.ProtoReflect.Descriptor instead.
func (*ReportDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_orchestrator_proto_rawDescGZIP(), []int{11}
}

var File_proto_orchestrator_orchestrator_proto protoreflect.FileDescriptor

const file_proto_orchestrator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"%proto/orchestrator/orchestrator.proto\x12\forchestrator\"\x1a\n" +
	"\x12ListDevicesRequestJ\x04\b\x01\x10\x02\"F\n" +
	"\n" +
	"DeviceList\x128\n" +
	"\asources\x18\x01 \x03(\v2\x1e.orchestrator.DeviceSourceInfoR\asources\"\x95\x01\n" +
	"\x10DeviceSourceInfo\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x122\n" +
	"\adevices\x18\x04 \x03(\v2\x18.orchestrator.DeviceInfoR\adevices\"\x9e\x01\n" +
	"\n" +
	"DeviceInfo\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x10\n" +
	"\x03sdk\x18\x04 \x01(\x05R\x03sdk\x12\x18\n" +
	"\arelease\x18\x05 \x01(\x05R\arelease\x12\x12\n" +
	"\x04busy\x18\x06 \x01(\bR\x04busy\"B\n" +
	"\x12AcquireLockRequest\x12\x18\n" +
	"\aserials\x18\x01 \x03(\tR\aserials\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"H\n" +
	"\x13AcquireLockResponse\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x18\n" +
	"\aserials\x18\x02 \x03(\tR\aserials\"-\n" +
	"\x12ReleaseLockRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"1\n" +
	"\x13ReleaseLockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"/\n" +
	"\x14LockHeartbeatRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"-\n" +
	"\x15LockHeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\"J\n" +
	"\x14ReportDevicesRequest\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.orchestrator.DeviceInfoR\adevices\"\x17\n" +
	"\x15ReportDevicesResponse2\xbf\x03\n" +
	"\fOrchestrator\x12K\n" +
	"\vListDevices\x12 .orchestrator.ListDevicesRequest\x1a\x18.orchestrator.DeviceList\"\x00\x12T\n" +
	"\vAcquireLock\x12 .orchestrator.AcquireLockRequest\x1a!.orchestrator.AcquireLockResponse\"\x00\x12T\n" +
	"\vReleaseLock\x12 .orchestrator.ReleaseLockRequest\x1a!.orchestrator.ReleaseLockResponse\"\x00\x12Z\n" +
	"\rLockHeartbeat\x12\".orchestrator.LockHeartbeatRequest\x1a#.orchestrator.LockHeartbeatResponse\"\x00\x12Z\n" +
	"\rReportDevices\x12\".orchestrator.ReportDevicesRequest\x1a#.orchestrator.ReportDevicesResponse\"\x00B.Z,github.com/compscidr/sair/proto/orchestratorb\x06proto3"

var (
	file_proto_orchestrator_orchestrator_proto_rawDescOnce sync.Once
	file_proto_orchestrator_orchestrator_proto_rawDescData []byte
)

func file_proto_orchestrator_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)))
	})
	return file_proto_orchestrator_orchestrator_proto_rawDescData
}

var file_proto_orchestrator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_orchestrator_orchestrator_proto_goTypes = []any{
	(*ListDevicesRequest)(nil),    // 0: orchestrator.ListDevicesRequest
	(*DeviceList)(nil),            // 1: orchestrator.DeviceList
	(*DeviceSourceInfo)(nil),      // 2: orchestrator.DeviceSourceInfo
	(*DeviceInfo)(nil),            // 3: orchestrator.DeviceInfo
	(*AcquireLockRequest)(nil),    // 4: orchestrator.AcquireLockRequest
	(*AcquireLockResponse)(nil),   // 5: orchestrator.AcquireLockResponse
	(*ReleaseLockRequest)(nil),    // 6: orchestrator.ReleaseLockRequest
	(*ReleaseLockResponse)(nil),   // 7: orchestrator.ReleaseLockResponse
	(*LockHeartbeatRequest)(nil),  // 8: orchestrator.LockHeartbeatRequest
	(*LockHeartbeatResponse)(nil), // 9: orchestrator.LockHeartbeatResponse
	(*ReportDevicesRequest)(nil),  // 10: orchestrator.ReportDevicesRequest
	(*ReportDevicesResponse)(nil), // 11: orchestrator.ReportDevicesResponse
}
var file_proto_orchestrator_orchestrator_proto_depIdxs = []int32{
	2,  // 0: orchestrator.DeviceList.sources:type_name -> orchestrator.DeviceSourceInfo
	3,  // 1: orchestrator.DeviceSourceInfo.devices:type_name -> orchestrator.DeviceInfo
	3,  // 2: orchestrator.ReportDevicesRequest.devices:type_name -> orchestrator.DeviceInfo
	0,  // 3: orchestrator.Orchestrator.ListDevices:input_type -> orchestrator.ListDevicesRequest
	4,  // 4: orchestrator.Orchestrator.AcquireLock:input_type -> orchestrator.AcquireLockRequest
	6,  // 5: orchestrator.Orchestrator.ReleaseLock:input_type -> orchestrator.ReleaseLockRequest
	8,  // 6: orchestrator.Orchestrator.LockHeartbeat:input_type -> orchestrator.LockHeartbeatRequest
	10, // 7: orchestrator.Orchestrator.ReportDevices:input_type -> orchestrator.ReportDevicesRequest
	1,  // 8: orchestrator.Orchestrator.ListDevices:output_type -> orchestrator.DeviceList
	5,  // 9: orchestrator.Orchestrator.AcquireLock:output_type -> orchestrator.AcquireLockResponse
	7,  // 10: orchestrator.Orchestrator.ReleaseLock:output_type -> orchestrator.ReleaseLockResponse
	9,  // 11: orchestrator.Orchestrator.LockHeartbeat:output_type -> orchestrator.LockHeartbeatResponse
	11, // 12: orchestrator.Orchestrator.ReportDevices:output_type -> orchestrator.ReportDevicesResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_orchestrator_proto_init() }
func file_proto_orchestrator_orchestrator_proto_init() {
	if File_proto_orchestrator_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_orchestrator_proto_rawDesc), len(file_proto_orchestrator_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_orchestrator_proto_depIdxs,
		MessageInfos:      file_proto_orchestrator_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_orchestrator_proto = out.File
	file_proto_orchestrator_orchestrator_proto_goTypes = nil
	file_proto_orchestrator_orchestrator_proto_depIdxs = nil
}
