// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/devicesource/devicesource.proto

package devicesource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WifiRequest_State int32

const (
	// Forget every shell-added suggestion and saved network, then toggle the
	// radio: on, nothing registered, not associated. Used on release.
	WifiRequest_RESET WifiRequest_State = 0
	// Forget suggestions and saved networks; the radio stays on.
	WifiRequest_OFF WifiRequest_State = 1
	// Suggest the bench network and wait until the device reaches the Internet.
	WifiRequest_ON WifiRequest_State = 2
)

// Enum value maps for WifiRequest_State.
var (
	WifiRequest_State_name = map[int32]string{
		0: "RESET",
		1: "OFF",
		2: "ON",
	}
	WifiRequest_State_value = map[string]int32{
		"RESET": 0,
		"OFF":   1,
		"ON":    2,
	}
)

func (x WifiRequest_State) Enum() *WifiRequest_State {
	p := new(WifiRequest_State)
	*p = x
	return p
}

func (x WifiRequest_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiRequest_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicesource_devicesource_proto_enumTypes[0].Descriptor()
}

func (WifiRequest_State) Type() protoreflect.EnumType {
	return &file_proto_devicesource_devicesource_proto_enumTypes[0]
}

func (x WifiRequest_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiRequest_State.Descriptor instead.
func (WifiRequest_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{0, 0}
}

type WifiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	State         WifiRequest_State      `protobuf:"varint,2,opt,name=state,proto3,enum=devicesource.WifiRequest_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiRequest) Reset() {
	*x = WifiRequest{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiRequest) ProtoMessage() {}

func (x *WifiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiRequest.ProtoReflect.Descriptor instead.
func (*WifiRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{0}
}

func (x *WifiRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *WifiRequest) GetState() WifiRequest_State {
	if x != nil {
		return x.State
	}
	return WifiRequest_RESET
}

type Devices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Devices) Reset() {
	*x = Devices{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{1}
}

func (x *Devices) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Release       int32                  `protobuf:"varint,4,opt,name=release,proto3" json:"release,omitempty"`
	Sdk           int32                  `protobuf:"varint,5,opt,name=sdk,proto3" json:"sdk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Device) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetRelease() int32 {
	if x != nil {
		return x.Release
	}
	return 0
}

func (x *Device) GetSdk() int32 {
	if x != nil {
		return x.Sdk
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type DeviceCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Serial         string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceCommand) Reset() {
	*x = DeviceCommand{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommand) ProtoMessage() {}

func (x *DeviceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommand.ProtoReflect.Descriptor instead.
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceCommand) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DeviceCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceInQueue  int32                  `protobuf:"varint,1,opt,name=place_in_queue,json=placeInQueue,proto3" json:"place_in_queue,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetPlaceInQueue() int32 {
	if x != nil {
		return x.PlaceInQueue
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ForwardData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ForwardData_Setup
	//	*ForwardData_Data
	Payload       isForwardData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardData) Reset() {
	*x = ForwardData{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardData) ProtoMessage() {}

func (x *ForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardData.ProtoReflect.Descriptor instead.
func (*ForwardData) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardData) GetPayload() isForwardData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardData) GetSetup() *ForwardSetup {
	if x != nil {
		if x, ok := x.Payload.(*ForwardData_Setup); ok {
			return x.Setup
		}
	}
	return nil
}

func (x *ForwardData) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ForwardData_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isForwardData_Payload interface {
	isForwardData_Payload()
}

type ForwardData_Setup struct {
	Setup *ForwardSetup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type ForwardData_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ForwardData_Setup) isForwardData_Payload() {}

func (*ForwardData_Data) isForwardData_Payload() {}

type ForwardSetup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Serial         string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	InitialCommand string                 `protobuf:"bytes,2,opt,name=initial_command,json=initialCommand,proto3" json:"initial_command,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardSetup) Reset() {
	*x = ForwardSetup{}
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardSetup) ProtoMessage() {}

func (x *ForwardSetup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicesource_devicesource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardSetup.ProtoReflect.Descriptor instead.
func (*ForwardSetup) Descriptor() ([]byte, []int) {
	return file_proto_devicesource_devicesource_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardSetup) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *ForwardSetup) GetInitialCommand() string {
	if x != nil {
		return x.InitialCommand
	}
	return ""
}

var File_proto_devicesource_devicesource_proto protoreflect.FileDescriptor

const file_proto_devicesource_devicesource_proto_rawDesc = "" +
	"\n" +
	"%proto/devicesource/devicesource.proto\x12\fdevicesource\x1a\x1bgoogle/protobuf/empty.proto\"\x81\x01\n" +
	"\vWifiRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.devicesource.WifiRequest.StateR\x05state\"#\n" +
	"\x05State\x12\t\n" +
	"\x05RESET\x10\x00\x12\a\n" +
	"\x03OFF\x10\x01\x12\x06\n" +
	"\x02ON\x10\x02\"9\n" +
	"\aDevices\x12.\n" +
	"\adevices\x18\x01 \x03(\v2\x14.devicesource.DeviceR\adevices\"\x86\x01\n" +
	"\x06Device\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x18\n" +
	"\arelease\x18\x04 \x01(\x05R\arelease\x12\x10\n" +
	"\x03sdk\x18\x05 \x01(\x05R\x03sdk\"\x1b\n" +
	"\aCommand\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"j\n" +
	"\rDeviceCommand\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\x82\x01\n" +
	"\rCommandResult\x12$\n" +
	"\x0eplace_in_queue\x18\x01 \x01(\x05R\fplaceInQueue\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"b\n" +
	"\vForwardData\x122\n" +
	"\x05setup\x18\x01 \x01(\v2\x1a.devicesource.ForwardSetupH\x00R\x05setup\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"O\n" +
	"\fForwardSetup\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12'\n" +
	"\x0finitial_command\x18\x02 \x01(\tR\x0einitialCommand2\xf4\x02\n" +
	"\fDeviceSource\x12=\n" +
	"\n" +
	"GetDevices\x12\x16.google.protobuf.Empty\x1a\x15.devicesource.Devices\"\x00\x12H\n" +
	"\x0eEnqueueCommand\x12\x15.devicesource.Command\x1a\x1b.devicesource.CommandResult\"\x000\x01\x12L\n" +
	"\fExecOnDevice\x12\x1b.devicesource.DeviceCommand\x1a\x1b.devicesource.CommandResult\"\x000\x01\x12M\n" +
	"\x0fForwardToDevice\x12\x19.devicesource.ForwardData\x1a\x19.devicesource.ForwardData\"\x00(\x010\x01\x12>\n" +
	"\aSetWifi\x12\x19.devicesource.WifiRequest\x1a\x16.google.protobuf.Empty\"\x00B.Z,github.com/compscidr/sair/proto/devicesourceb\x06proto3"

var (
	file_proto_devicesource_devicesource_proto_rawDescOnce sync.Once
	file_proto_devicesource_devicesource_proto_rawDescData []byte
)

func file_proto_devicesource_devicesource_proto_rawDescGZIP() []byte {
	file_proto_devicesource_devicesource_proto_rawDescOnce.Do(func() {
		file_proto_devicesource_devicesource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicesource_devicesource_proto_rawDesc), len(file_proto_devicesource_devicesource_proto_rawDesc)))
	})
	return file_proto_devicesource_devicesource_proto_rawDescData
}

var file_proto_devicesource_devicesource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_devicesource_devicesource_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_devicesource_devicesource_proto_goTypes = []any{
	(WifiRequest_State)(0), // 0: devicesource.WifiRequest.State
	(*WifiRequest)(nil),    // 1: devicesource.WifiRequest
	(*Devices)(nil),        // 2: devicesource.Devices
	(*Device)(nil),         // 3: devicesource.Device
	(*Command)(nil),        // 4: devicesource.Command
	(*DeviceCommand)(nil),  // 5: devicesource.DeviceCommand
	(*CommandResult)(nil),  // 6: devicesource.CommandResult
	(*ForwardData)(nil),    // 7: devicesource.ForwardData
	(*ForwardSetup)(nil),   // 8: devicesource.ForwardSetup
	(*emptypb.Empty)(nil),  // 9: google.protobuf.Empty
}
var file_proto_devicesource_devicesource_proto_depIdxs = []int32{
	0, // 0: devicesource.WifiRequest.state:type_name -> devicesource.WifiRequest.State
	3, // 1: devicesource.Devices.devices:type_name -> devicesource.Device
	8, // 2: devicesource.ForwardData.setup:type_name -> devicesource.ForwardSetup
	9, // 3: devicesource.DeviceSource.GetDevices:input_type -> google.protobuf.Empty
	4, // 4: devicesource.DeviceSource.EnqueueCommand:input_type -> devicesource.Command
	5, // 5: devicesource.DeviceSource.ExecOnDevice:input_type -> devicesource.DeviceCommand
	7, // 6: devicesource.DeviceSource.ForwardToDevice:input_type -> devicesource.ForwardData
	1, // 7: devicesource.DeviceSource.SetWifi:input_type -> devicesource.WifiRequest
	2, // 8: devicesource.DeviceSource.GetDevices:output_type -> devicesource.Devices
	6, // 9: devicesource.DeviceSource.EnqueueCommand:output_type -> devicesource.CommandResult
	6, // 10: devicesource.DeviceSource.ExecOnDevice:output_type -> devicesource.CommandResult
	7, // 11: devicesource.DeviceSource.ForwardToDevice:output_type -> devicesource.ForwardData
	9, // 12: devicesource.DeviceSource.SetWifi:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_devicesource_devicesource_proto_init() }
func file_proto_devicesource_devicesource_proto_init() {
	if File_proto_devicesource_devicesource_proto != nil {
		return
	}
	file_proto_devicesource_devicesource_proto_msgTypes[6].OneofWrappers = []any{
		(*ForwardData_Setup)(nil),
		(*ForwardData_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicesource_devicesource_proto_rawDesc), len(file_proto_devicesource_devicesource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_devicesource_devicesource_proto_goTypes,
		DependencyIndexes: file_proto_devicesource_devicesource_proto_depIdxs,
		EnumInfos:         file_proto_devicesource_devicesource_proto_enumTypes,
		MessageInfos:      file_proto_devicesource_devicesource_proto_msgTypes,
	}.Build()
	File_proto_devicesource_devicesource_proto = out.File
	file_proto_devicesource_devicesource_proto_goTypes = nil
	file_proto_devicesource_devicesource_proto_depIdxs = nil
}
