// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/devicesource/devicesource.proto

package devicesource

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceSource_GetDevices_FullMethodName      = "/devicesource.DeviceSource/GetDevices"
	DeviceSource_EnqueueCommand_FullMethodName  = "/devicesource.DeviceSource/EnqueueCommand"
	DeviceSource_ExecOnDevice_FullMethodName    = "/devicesource.DeviceSource/ExecOnDevice"
	DeviceSource_ForwardToDevice_FullMethodName = "/devicesource.DeviceSource/ForwardToDevice"
)

// DeviceSourceClient is the client API for DeviceSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceSourceClient interface {
	GetDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Devices, error)
	EnqueueCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResult], error)
	// Execute a command on a specific device identified by serial number
	ExecOnDevice(ctx context.Context, in *DeviceCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResult], error)
	// Bidirectional raw byte forwarding to a device via the real ADB server.
	// Used for protocols like sync: that the proxy cannot interpret.
	ForwardToDevice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardData, ForwardData], error)
}

type deviceSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceSourceClient(cc grpc.ClientConnInterface) DeviceSourceClient {
	return &deviceSourceClient{cc}
}

func (c *deviceSourceClient) GetDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Devices, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Devices)
	err := c.cc.Invoke(ctx, DeviceSource_GetDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceSourceClient) EnqueueCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceSource_ServiceDesc.Streams[0], DeviceSource_EnqueueCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Command, CommandResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceSource_EnqueueCommandClient = grpc.ServerStreamingClient[CommandResult]

func (c *deviceSourceClient) ExecOnDevice(ctx context.Context, in *DeviceCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceSource_ServiceDesc.Streams[1], DeviceSource_ExecOnDevice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviceCommand, CommandResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceSource_ExecOnDeviceClient = grpc.ServerStreamingClient[CommandResult]

func (c *deviceSourceClient) ForwardToDevice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardData, ForwardData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceSource_ServiceDesc.Streams[2], DeviceSource_ForwardToDevice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardData, ForwardData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceSource_ForwardToDeviceClient = grpc.BidiStreamingClient[ForwardData, ForwardData]

// DeviceSourceServer is the server API for DeviceSource service.
// All implementations must embed UnimplementedDeviceSourceServer
// for forward compatibility.
type DeviceSourceServer interface {
	GetDevices(context.Context, *emptypb.Empty) (*Devices, error)
	EnqueueCommand(*Command, grpc.ServerStreamingServer[CommandResult]) error
	// Execute a command on a specific device identified by serial number
	ExecOnDevice(*DeviceCommand, grpc.ServerStreamingServer[CommandResult]) error
	// Bidirectional raw byte forwarding to a device via the real ADB server.
	// Used for protocols like sync: that the proxy cannot interpret.
	ForwardToDevice(grpc.BidiStreamingServer[ForwardData, ForwardData]) error
	mustEmbedUnimplementedDeviceSourceServer()
}

// UnimplementedDeviceSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceSourceServer struct{}

func (UnimplementedDeviceSourceServer) GetDevices(context.Context, *emptypb.Empty) (*Devices, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedDeviceSourceServer) EnqueueCommand(*Command, grpc.ServerStreamingServer[CommandResult]) error {
	return status.Error(codes.Unimplemented, "method EnqueueCommand not implemented")
}
func (UnimplementedDeviceSourceServer) ExecOnDevice(*DeviceCommand, grpc.ServerStreamingServer[CommandResult]) error {
	return status.Error(codes.Unimplemented, "method ExecOnDevice not implemented")
}
func (UnimplementedDeviceSourceServer) ForwardToDevice(grpc.BidiStreamingServer[ForwardData, ForwardData]) error {
	return status.Error(codes.Unimplemented, "method ForwardToDevice not implemented")
}
func (UnimplementedDeviceSourceServer) mustEmbedUnimplementedDeviceSourceServer() {}
func (UnimplementedDeviceSourceServer) testEmbeddedByValue()                      {}

// UnsafeDeviceSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceSourceServer will
// result in compilation errors.
type UnsafeDeviceSourceServer interface {
	mustEmbedUnimplementedDeviceSourceServer()
}

func RegisterDeviceSourceServer(s grpc.ServiceRegistrar, srv DeviceSourceServer) {
	// If the following call panics, it indicates UnimplementedDeviceSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceSource_ServiceDesc, srv)
}

func _DeviceSource_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceSourceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceSource_GetDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceSourceServer).GetDevices(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceSource_EnqueueCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Command)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceSourceServer).EnqueueCommand(m, &grpc.GenericServerStream[Command, CommandResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceSource_EnqueueCommandServer = grpc.ServerStreamingServer[CommandResult]

func _DeviceSource_ExecOnDevice_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeviceCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceSourceServer).ExecOnDevice(m, &grpc.GenericServerStream[DeviceCommand, CommandResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceSource_ExecOnDeviceServer = grpc.ServerStreamingServer[CommandResult]

func _DeviceSource_ForwardToDevice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceSourceServer).ForwardToDevice(&grpc.GenericServerStream[ForwardData, ForwardData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceSource_ForwardToDeviceServer = grpc.BidiStreamingServer[ForwardData, ForwardData]

// DeviceSource_ServiceDesc is the grpc.ServiceDesc for DeviceSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicesource.DeviceSource",
	HandlerType: (*DeviceSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _DeviceSource_GetDevices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EnqueueCommand",
			Handler:       _DeviceSource_EnqueueCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecOnDevice",
			Handler:       _DeviceSource_ExecOnDevice_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ForwardToDevice",
			Handler:       _DeviceSource_ForwardToDevice_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/devicesource/devicesource.proto",
}
